baseURL = 'http://blog.mio.am/'
languageCode = 'zh-cn'
title = "<Miourasaki>'s Blog"
theme = "new_paper"

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'https://twitter.com/@Miourasaki'               # twitter.com/YOUR_TWITTER_ID
  github = 'https://github.com/Miourasaki'                 # github.com/YOUR_GITHUB_ID
  bilibili = 'https://space.bilibili.com/94209973'           # instagram.com/YOUR_INSTAGRAM_ID
  telegrame = 'https://1oli.cn/tg'             # linkedin.com/in/YOUR_LINKEDIN_ID
  website = 'https://mio.am'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'mio@chyan.moe'                 # gravatar email or image url
  name = '白澪'
  bio = '#少女祈祷中~'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.lolis.fyi/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

  # giscus
[params.giscus]
  repo = 'YOUR_GISCUS_REPO'                 # see https://giscus.app for more details
  repoId = 'YOUR_GISCUS_REPO_ID'
  category = 'YOUR__GISCUS_CATEGORY'
  categoryId = 'YOUR_GISCUS_CATEGORY_ID'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'