name: Deploy to Web Branch

on:
  push:
    branches:
      - master  # 触发动作的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取全部历史以便能够操作各个分支

      - name: Configure Git
        run: |
          git config --global user.email "mio@chyan.moe"
          git config --global user.name "Miourasaki"

      - name: Copy public to web branch
        run: |
          # 创建一个临时目录来存放public目录的内容
          mkdir tmp-public
          # 复制public目录内容到临时目录
          cp -r public/* tmp-public
          # 切换到web分支，如果不存在则创建并从空白开始
          git checkout web || git checkout --orphan web
          # 清除web分支当前的所有文件（如果有）
          git rm -rf . || true
          # 将临时目录中的内容移动到工作目录
          mv tmp-public/* . && mv tmp-public/.* . || true
          # 删除临时目录
          rmdir tmp-public
          # 检查是否有文件变动（避免无变动时的失败提交）
          if git status | grep -q "Changes to be committed"; then
            git add .
            git commit -m "Update web content"
            git push origin web
          else
            echo "No changes detected, skipping."